
# SEO settings
title: drbits
description: "Bits of Tech and Business from Daniel Rice"
keywords: "Fintech, blockchain, bitcoin, smart contract, risk"
url: ""
baseurl: ""
# baseurl: null

timezone: America/Los_Angeles

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

paginate: 4
paginate_path: "/page/:num/"
comments: false

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : Daniel Rice
  job      : "Computer Scientist and Chief Technology Officer focused on fintech. I'm currently working at <a href=https://www.sagewise.io>Sagewise</a> where I am co-founder and CTO. Our published active products are <a href=https://www.blokusign.com>Blokusign</a> and <a href=https://www.getloaded.app>Loaded</a>"
  bio      : "These are my thoughts on Technology and Business."
  thumb    : /images/author.jpg
  email    : dan@drbits.org
  github   : http://github.com/thedrbits
  twitter  : http://twitter.com/thedrbits

# social settings
twitter_card: "summary_large_image"
twitter_site: "@thedrbits"

plugins:
  - jekyll-paginate

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
